"""Exercise seed data — idempotent upsert-by-name seeding for the exercises collection."""

from pymongo import UpdateOne

from app.exercises.models import Exercise

SEED_EXERCISES = [
    # ── Chest (22 entries) ──────────────────────────────────────────────────
    {"name": "Barbell Bench Press", "muscle_group": "Chest", "equipment": "Barbell",
     "name_ru": "Жим штанги лёжа", "gif_url": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Bench_press_2.gif"},
    {"name": "Incline Barbell Press", "muscle_group": "Chest", "equipment": "Barbell",
     "name_ru": "Жим штанги на наклонной скамье", "gif_url": None},
    {"name": "Decline Bench Press", "muscle_group": "Chest", "equipment": "Barbell",
     "name_ru": "Жим штанги на скамье с отрицательным наклоном", "gif_url": None},
    {"name": "Incline Dumbbell Press", "muscle_group": "Chest", "equipment": "Dumbbell",
     "name_ru": "Жим гантелей на наклонной скамье", "gif_url": None},
    {"name": "Flat Dumbbell Press", "muscle_group": "Chest", "equipment": "Dumbbell",
     "name_ru": "Жим гантелей лёжа", "gif_url": None},
    {"name": "Decline Dumbbell Press", "muscle_group": "Chest", "equipment": "Dumbbell",
     "name_ru": "Жим гантелей на скамье с отрицательным наклоном", "gif_url": None},
    {"name": "Dumbbell Fly", "muscle_group": "Chest", "equipment": "Dumbbell",
     "name_ru": "Разводка гантелей лёжа", "gif_url": None},
    {"name": "Incline Dumbbell Fly", "muscle_group": "Chest", "equipment": "Dumbbell",
     "name_ru": "Разводка гантелей на наклонной скамье", "gif_url": None},
    {"name": "Cable Fly", "muscle_group": "Chest", "equipment": "Cable",
     "name_ru": "Кроссовер на кабеле", "gif_url": None},
    {"name": "Low Cable Fly", "muscle_group": "Chest", "equipment": "Cable",
     "name_ru": "Кроссовер снизу вверх", "gif_url": None},
    {"name": "High Cable Fly", "muscle_group": "Chest", "equipment": "Cable",
     "name_ru": "Кроссовер сверху вниз", "gif_url": None},
    {"name": "Machine Chest Press", "muscle_group": "Chest", "equipment": "Machine",
     "name_ru": "Жим в тренажёре лёжа", "gif_url": None},
    {"name": "Machine Fly", "muscle_group": "Chest", "equipment": "Machine",
     "name_ru": "Разводка в тренажёре (бабочка)", "gif_url": None},
    {"name": "Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Отжимания", "gif_url": None},
    {"name": "Wide Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Отжимания широким хватом", "gif_url": None},
    {"name": "Diamond Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Отжимания узким хватом (алмаз)", "gif_url": None},
    {"name": "Incline Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Отжимания на возвышенности", "gif_url": None},
    {"name": "Chest Dip", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Отжимания на брусьях (грудь)", "gif_url": None},
    {"name": "Svend Press", "muscle_group": "Chest", "equipment": "Barbell",
     "name_ru": "Жим Свенда", "gif_url": None},
    {"name": "Landmine Press", "muscle_group": "Chest", "equipment": "Barbell",
     "name_ru": "Жим в рычажном тренажёре (ландмина)", "gif_url": None},
    {"name": "Smith Machine Bench Press", "muscle_group": "Chest", "equipment": "Machine",
     "name_ru": "Жим в машине Смита лёжа", "gif_url": None},
    {"name": "Resistance Band Fly", "muscle_group": "Chest", "equipment": "Bodyweight",
     "name_ru": "Разводка с эспандером", "gif_url": None},

    # ── Back (23 entries) ───────────────────────────────────────────────────
    {"name": "Barbell Row", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Тяга штанги в наклоне", "gif_url": None},
    {"name": "Pendlay Row", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Тяга Пендлея", "gif_url": None},
    {"name": "T-Bar Row", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Тяга Т-грифа", "gif_url": None},
    {"name": "Deadlift", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Становая тяга", "gif_url": None},
    {"name": "Sumo Deadlift", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Становая тяга сумо", "gif_url": None},
    {"name": "Rack Pull", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Тяга с плинтов", "gif_url": None},
    {"name": "Pull-Up", "muscle_group": "Back", "equipment": "Bodyweight",
     "name_ru": "Подтягивания", "gif_url": None},
    {"name": "Chin-Up", "muscle_group": "Back", "equipment": "Bodyweight",
     "name_ru": "Подтягивания обратным хватом", "gif_url": None},
    {"name": "Wide-Grip Pull-Up", "muscle_group": "Back", "equipment": "Bodyweight",
     "name_ru": "Подтягивания широким хватом", "gif_url": None},
    {"name": "Lat Pulldown", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга верхнего блока", "gif_url": None},
    {"name": "Close-Grip Lat Pulldown", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга верхнего блока узким хватом", "gif_url": None},
    {"name": "Seated Cable Row", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга нижнего блока сидя", "gif_url": None},
    {"name": "Single-Arm Cable Row", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга блока одной рукой", "gif_url": None},
    {"name": "Face Pull", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга к лицу", "gif_url": None},
    {"name": "Straight-Arm Pulldown", "muscle_group": "Back", "equipment": "Cable",
     "name_ru": "Тяга верхнего блока прямыми руками", "gif_url": None},
    {"name": "Dumbbell Row", "muscle_group": "Back", "equipment": "Dumbbell",
     "name_ru": "Тяга гантели в наклоне", "gif_url": None},
    {"name": "Chest-Supported Dumbbell Row", "muscle_group": "Back", "equipment": "Dumbbell",
     "name_ru": "Тяга гантелей с упором в скамью", "gif_url": None},
    {"name": "Machine Row", "muscle_group": "Back", "equipment": "Machine",
     "name_ru": "Тяга в тренажёре горизонтальная", "gif_url": None},
    {"name": "Machine Pullover", "muscle_group": "Back", "equipment": "Machine",
     "name_ru": "Пуловер в тренажёре", "gif_url": None},
    {"name": "Dumbbell Pullover", "muscle_group": "Back", "equipment": "Dumbbell",
     "name_ru": "Пуловер с гантелью", "gif_url": None},
    {"name": "Good Morning", "muscle_group": "Back", "equipment": "Barbell",
     "name_ru": "Наклоны со штангой (гудмонинг)", "gif_url": None},
    {"name": "Back Extension", "muscle_group": "Back", "equipment": "Bodyweight",
     "name_ru": "Гиперэкстензия", "gif_url": None},
    {"name": "Inverted Row", "muscle_group": "Back", "equipment": "Bodyweight",
     "name_ru": "Австралийские подтягивания", "gif_url": None},

    # ── Shoulders (22 entries) ──────────────────────────────────────────────
    {"name": "Overhead Press", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Жим штанги стоя", "gif_url": None},
    {"name": "Push Press", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Толчок штанги", "gif_url": None},
    {"name": "Seated Barbell Press", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Жим штанги сидя", "gif_url": None},
    {"name": "Arnold Press", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Жим Арнольда", "gif_url": None},
    {"name": "Dumbbell Shoulder Press", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Жим гантелей сидя", "gif_url": None},
    {"name": "Lateral Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Разводка гантелей в стороны", "gif_url": None},
    {"name": "Cable Lateral Raise", "muscle_group": "Shoulders", "equipment": "Cable",
     "name_ru": "Разводка на блоке в сторону", "gif_url": None},
    {"name": "Front Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Подъём гантелей перед собой", "gif_url": None},
    {"name": "Barbell Front Raise", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Подъём штанги перед собой", "gif_url": None},
    {"name": "Reverse Fly", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Обратная разводка гантелей", "gif_url": None},
    {"name": "Reverse Pec Deck", "muscle_group": "Shoulders", "equipment": "Machine",
     "name_ru": "Обратная бабочка в тренажёре", "gif_url": None},
    {"name": "Barbell Upright Row", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Тяга штанги к подбородку", "gif_url": None},
    {"name": "Cable Upright Row", "muscle_group": "Shoulders", "equipment": "Cable",
     "name_ru": "Тяга блока к подбородку", "gif_url": None},
    {"name": "Machine Shoulder Press", "muscle_group": "Shoulders", "equipment": "Machine",
     "name_ru": "Жим в тренажёре сидя", "gif_url": None},
    {"name": "Behind-the-Neck Press", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Жим штанги из-за головы", "gif_url": None},
    {"name": "Dumbbell Shrug", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Шраги с гантелями", "gif_url": None},
    {"name": "Barbell Shrug", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Шраги со штангой", "gif_url": None},
    {"name": "Cable Shrug", "muscle_group": "Shoulders", "equipment": "Cable",
     "name_ru": "Шраги на блоке", "gif_url": None},
    {"name": "Landmine Lateral Raise", "muscle_group": "Shoulders", "equipment": "Barbell",
     "name_ru": "Разводка с ландминой", "gif_url": None},
    {"name": "Band Pull-Apart", "muscle_group": "Shoulders", "equipment": "Bodyweight",
     "name_ru": "Разводка с лентой", "gif_url": None},
    {"name": "Seated Dumbbell Lateral Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell",
     "name_ru": "Разводка гантелей в стороны сидя", "gif_url": None},
    {"name": "Cable Front Raise", "muscle_group": "Shoulders", "equipment": "Cable",
     "name_ru": "Подъём на блоке перед собой", "gif_url": None},

    # ── Arms (25 entries) ───────────────────────────────────────────────────
    {"name": "Barbell Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Сгибание рук со штангой", "gif_url": None},
    {"name": "EZ-Bar Curl", "muscle_group": "Arms", "equipment": "EZ Bar",
     "name_ru": "Сгибание рук с EZ-штангой", "gif_url": None},
    {"name": "Dumbbell Curl", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Сгибание рук с гантелями", "gif_url": None},
    {"name": "Hammer Curl", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Молотковые сгибания", "gif_url": None},
    {"name": "Incline Dumbbell Curl", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Сгибание рук с гантелями на наклонной скамье", "gif_url": None},
    {"name": "Concentration Curl", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Концентрированные сгибания", "gif_url": None},
    {"name": "Preacher Curl", "muscle_group": "Arms", "equipment": "EZ Bar",
     "name_ru": "Сгибание рук на скамье Скотта", "gif_url": None},
    {"name": "Spider Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Паучьи сгибания", "gif_url": None},
    {"name": "Cable Curl", "muscle_group": "Arms", "equipment": "Cable",
     "name_ru": "Сгибание рук на блоке", "gif_url": None},
    {"name": "Reverse Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Сгибание рук обратным хватом", "gif_url": None},
    {"name": "Wrist Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Сгибание запястий", "gif_url": None},
    {"name": "Reverse Wrist Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Разгибание запястий", "gif_url": None},
    {"name": "Tricep Pushdown", "muscle_group": "Arms", "equipment": "Cable",
     "name_ru": "Разгибание рук на блоке", "gif_url": None},
    {"name": "Rope Pushdown", "muscle_group": "Arms", "equipment": "Cable",
     "name_ru": "Разгибание рук на блоке с канатом", "gif_url": None},
    {"name": "Overhead Tricep Extension", "muscle_group": "Arms", "equipment": "Cable",
     "name_ru": "Разгибание рук над головой на блоке", "gif_url": None},
    {"name": "Dumbbell Overhead Tricep Extension", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Французский жим с гантелью стоя", "gif_url": None},
    {"name": "Skull Crusher", "muscle_group": "Arms", "equipment": "EZ Bar",
     "name_ru": "Французский жим лёжа", "gif_url": None},
    {"name": "Close-Grip Bench Press", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Жим узким хватом", "gif_url": None},
    {"name": "Dip", "muscle_group": "Arms", "equipment": "Bodyweight",
     "name_ru": "Отжимания на брусьях", "gif_url": None},
    {"name": "Bench Dip", "muscle_group": "Arms", "equipment": "Bodyweight",
     "name_ru": "Отжимания от скамьи", "gif_url": None},
    {"name": "Kickback", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Разгибание руки с гантелью в наклоне", "gif_url": None},
    {"name": "Cable Kickback", "muscle_group": "Arms", "equipment": "Cable",
     "name_ru": "Разгибание руки на блоке в наклоне", "gif_url": None},
    {"name": "Zottman Curl", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Сгибание Зоттмана", "gif_url": None},
    {"name": "21s Curl", "muscle_group": "Arms", "equipment": "Barbell",
     "name_ru": "Сгибания 21 (семёрки)", "gif_url": None},
    {"name": "Tricep Dumbbell Kickback", "muscle_group": "Arms", "equipment": "Dumbbell",
     "name_ru": "Отведение гантели назад для трицепса", "gif_url": None},

    # ── Legs (27 entries) ───────────────────────────────────────────────────
    {"name": "Barbell Back Squat", "muscle_group": "Legs", "equipment": "Barbell",
     "name_ru": "Приседания со штангой", "gif_url": None},
    {"name": "Front Squat", "muscle_group": "Legs", "equipment": "Barbell",
     "name_ru": "Фронтальные приседания", "gif_url": None},
    {"name": "Hack Squat", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Гакк-приседания", "gif_url": None},
    {"name": "Goblet Squat", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Приседания с гантелью (бокал)", "gif_url": None},
    {"name": "Sumo Squat", "muscle_group": "Legs", "equipment": "Barbell",
     "name_ru": "Приседания сумо", "gif_url": None},
    {"name": "Bulgarian Split Squat", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Болгарские сплит-приседания", "gif_url": None},
    {"name": "Lunge", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Выпады", "gif_url": None},
    {"name": "Walking Lunge", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Ходячие выпады", "gif_url": None},
    {"name": "Reverse Lunge", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Обратные выпады", "gif_url": None},
    {"name": "Romanian Deadlift", "muscle_group": "Legs", "equipment": "Barbell",
     "name_ru": "Румынская тяга", "gif_url": None},
    {"name": "Single-Leg Romanian Deadlift", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Румынская тяга на одной ноге", "gif_url": None},
    {"name": "Leg Press", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Жим ногами", "gif_url": None},
    {"name": "Leg Curl", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Сгибание ног в тренажёре", "gif_url": None},
    {"name": "Seated Leg Curl", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Сгибание ног сидя", "gif_url": None},
    {"name": "Leg Extension", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Разгибание ног в тренажёре", "gif_url": None},
    {"name": "Calf Raise", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Подъём на носки стоя", "gif_url": None},
    {"name": "Seated Calf Raise", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Подъём на носки сидя", "gif_url": None},
    {"name": "Donkey Calf Raise", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Подъём на носки в наклоне (осёл)", "gif_url": None},
    {"name": "Hip Thrust", "muscle_group": "Legs", "equipment": "Barbell",
     "name_ru": "Ягодичный мост со штангой", "gif_url": None},
    {"name": "Glute Bridge", "muscle_group": "Legs", "equipment": "Bodyweight",
     "name_ru": "Ягодичный мост", "gif_url": None},
    {"name": "Step-Up", "muscle_group": "Legs", "equipment": "Dumbbell",
     "name_ru": "Зашагивания на платформу", "gif_url": None},
    {"name": "Box Jump", "muscle_group": "Legs", "equipment": "Bodyweight",
     "name_ru": "Запрыгивания на ящик", "gif_url": None},
    {"name": "Wall Sit", "muscle_group": "Legs", "equipment": "Bodyweight",
     "name_ru": "Стульчик у стены", "gif_url": None},
    {"name": "Nordic Curl", "muscle_group": "Legs", "equipment": "Bodyweight",
     "name_ru": "Скандинавские сгибания", "gif_url": None},
    {"name": "Smith Machine Squat", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Приседания в машине Смита", "gif_url": None},
    {"name": "Adductor Machine", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Приведение ног в тренажёре", "gif_url": None},
    {"name": "Abductor Machine", "muscle_group": "Legs", "equipment": "Machine",
     "name_ru": "Отведение ног в тренажёре", "gif_url": None},

    # ── Core (23 entries) ───────────────────────────────────────────────────
    {"name": "Plank", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Планка", "gif_url": None},
    {"name": "Side Plank", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Боковая планка", "gif_url": None},
    {"name": "Cable Crunch", "muscle_group": "Core", "equipment": "Cable",
     "name_ru": "Скручивания на блоке", "gif_url": None},
    {"name": "Decline Sit-Up", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Скручивания на наклонной скамье", "gif_url": None},
    {"name": "Crunch", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Скручивания", "gif_url": None},
    {"name": "Bicycle Crunch", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Велосипедные скручивания", "gif_url": None},
    {"name": "Hanging Leg Raise", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Подъём ног в висе", "gif_url": None},
    {"name": "Hanging Knee Raise", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Подъём колен в висе", "gif_url": None},
    {"name": "Lying Leg Raise", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Подъём ног лёжа", "gif_url": None},
    {"name": "Russian Twist", "muscle_group": "Core", "equipment": "Dumbbell",
     "name_ru": "Русские скручивания", "gif_url": None},
    {"name": "Ab Wheel Rollout", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Ролик для пресса", "gif_url": None},
    {"name": "Pallof Press", "muscle_group": "Core", "equipment": "Cable",
     "name_ru": "Жим Паллофа", "gif_url": None},
    {"name": "Wood Chop", "muscle_group": "Core", "equipment": "Cable",
     "name_ru": "Рубка дров на блоке", "gif_url": None},
    {"name": "Dragon Flag", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Флаг дракона", "gif_url": None},
    {"name": "Hollow Body Hold", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Удержание полого тела", "gif_url": None},
    {"name": "V-Up", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Складка", "gif_url": None},
    {"name": "Toe Touch", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Касание носков лёжа", "gif_url": None},
    {"name": "Windshield Wiper", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Дворники", "gif_url": None},
    {"name": "Mountain Climber", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Бегущий по горам", "gif_url": None},
    {"name": "Dead Bug", "muscle_group": "Core", "equipment": "Bodyweight",
     "name_ru": "Мёртвый жук", "gif_url": None},
    {"name": "Farmer's Carry", "muscle_group": "Core", "equipment": "Dumbbell",
     "name_ru": "Прогулка фермера", "gif_url": None},
    {"name": "Suitcase Carry", "muscle_group": "Core", "equipment": "Dumbbell",
     "name_ru": "Прогулка с чемоданом", "gif_url": None},
    {"name": "Medicine Ball Slam", "muscle_group": "Core", "equipment": "Machine",
     "name_ru": "Бросок медицинского мяча", "gif_url": None},
]


# ── Exercise demo GIFs (self-hosted under frontend/public/gifs/, served same-origin at /gifs/*).
# Matched from the hasaneyldrm/exercises-dataset catalog; unmatched exercises keep gif_url=None.
GIF_URLS: dict[str, str] = {
    '21s Curl': "/gifs/21s-curl.gif",
    'Ab Wheel Rollout': "/gifs/ab-wheel-rollout.gif",
    'Abductor Machine': "/gifs/abductor-machine.gif",
    'Adductor Machine': "/gifs/adductor-machine.gif",
    'Arnold Press': "/gifs/arnold-press.gif",
    'Back Extension': "/gifs/back-extension.gif",
    'Barbell Back Squat': "/gifs/barbell-back-squat.gif",
    'Barbell Bench Press': "/gifs/barbell-bench-press.gif",
    'Barbell Curl': "/gifs/barbell-curl.gif",
    'Barbell Front Raise': "/gifs/barbell-front-raise.gif",
    'Barbell Row': "/gifs/barbell-row.gif",
    'Barbell Shrug': "/gifs/barbell-shrug.gif",
    'Barbell Upright Row': "/gifs/barbell-upright-row.gif",
    'Behind-the-Neck Press': "/gifs/behind-the-neck-press.gif",
    'Bench Dip': "/gifs/bench-dip.gif",
    'Bicycle Crunch': "/gifs/bicycle-crunch.gif",
    'Box Jump': "/gifs/box-jump.gif",
    'Bulgarian Split Squat': "/gifs/bulgarian-split-squat.gif",
    'Cable Crunch': "/gifs/cable-crunch.gif",
    'Cable Curl': "/gifs/cable-curl.gif",
    'Cable Fly': "/gifs/cable-fly.gif",
    'Cable Front Raise': "/gifs/cable-front-raise.gif",
    'Cable Kickback': "/gifs/cable-kickback.gif",
    'Cable Lateral Raise': "/gifs/cable-lateral-raise.gif",
    'Cable Shrug': "/gifs/cable-shrug.gif",
    'Cable Upright Row': "/gifs/cable-upright-row.gif",
    'Calf Raise': "/gifs/calf-raise.gif",
    'Chest Dip': "/gifs/chest-dip.gif",
    'Chest-Supported Dumbbell Row': "/gifs/chest-supported-dumbbell-row.gif",
    'Chin-Up': "/gifs/chin-up.gif",
    'Close-Grip Bench Press': "/gifs/close-grip-bench-press.gif",
    'Close-Grip Lat Pulldown': "/gifs/close-grip-lat-pulldown.gif",
    'Concentration Curl': "/gifs/concentration-curl.gif",
    'Crunch': "/gifs/crunch.gif",
    'Dead Bug': "/gifs/dead-bug.gif",
    'Deadlift': "/gifs/deadlift.gif",
    'Decline Bench Press': "/gifs/decline-bench-press.gif",
    'Decline Dumbbell Press': "/gifs/decline-dumbbell-press.gif",
    'Decline Sit-Up': "/gifs/decline-sit-up.gif",
    'Diamond Push-Up': "/gifs/diamond-push-up.gif",
    'Dip': "/gifs/dip.gif",
    'Donkey Calf Raise': "/gifs/donkey-calf-raise.gif",
    'Dragon Flag': "/gifs/dragon-flag.gif",
    'Dumbbell Curl': "/gifs/dumbbell-curl.gif",
    'Dumbbell Fly': "/gifs/dumbbell-fly.gif",
    'Dumbbell Overhead Tricep Extension': "/gifs/dumbbell-overhead-tricep-extension.gif",
    'Dumbbell Pullover': "/gifs/dumbbell-pullover.gif",
    'Dumbbell Row': "/gifs/dumbbell-row.gif",
    'Dumbbell Shoulder Press': "/gifs/dumbbell-shoulder-press.gif",
    'Dumbbell Shrug': "/gifs/dumbbell-shrug.gif",
    'EZ-Bar Curl': "/gifs/ez-bar-curl.gif",
    'Face Pull': "/gifs/face-pull.gif",
    "Farmer's Carry": "/gifs/farmer-s-carry.gif",
    'Flat Dumbbell Press': "/gifs/flat-dumbbell-press.gif",
    'Front Raise': "/gifs/front-raise.gif",
    'Front Squat': "/gifs/front-squat.gif",
    'Glute Bridge': "/gifs/glute-bridge.gif",
    'Goblet Squat': "/gifs/goblet-squat.gif",
    'Good Morning': "/gifs/good-morning.gif",
    'Hack Squat': "/gifs/hack-squat.gif",
    'Hammer Curl': "/gifs/hammer-curl.gif",
    'Hanging Knee Raise': "/gifs/hanging-knee-raise.gif",
    'Hanging Leg Raise': "/gifs/hanging-leg-raise.gif",
    'High Cable Fly': "/gifs/high-cable-fly.gif",
    'Incline Barbell Press': "/gifs/incline-barbell-press.gif",
    'Incline Dumbbell Curl': "/gifs/incline-dumbbell-curl.gif",
    'Incline Dumbbell Fly': "/gifs/incline-dumbbell-fly.gif",
    'Incline Dumbbell Press': "/gifs/incline-dumbbell-press.gif",
    'Incline Push-Up': "/gifs/incline-push-up.gif",
    'Inverted Row': "/gifs/inverted-row.gif",
    'Kickback': "/gifs/kickback.gif",
    'Landmine Lateral Raise': "/gifs/landmine-lateral-raise.gif",
    'Lat Pulldown': "/gifs/lat-pulldown.gif",
    'Lateral Raise': "/gifs/lateral-raise.gif",
    'Leg Curl': "/gifs/leg-curl.gif",
    'Leg Extension': "/gifs/leg-extension.gif",
    'Leg Press': "/gifs/leg-press.gif",
    'Low Cable Fly': "/gifs/low-cable-fly.gif",
    'Lunge': "/gifs/lunge.gif",
    'Lying Leg Raise': "/gifs/lying-leg-raise.gif",
    'Machine Chest Press': "/gifs/machine-chest-press.gif",
    'Machine Fly': "/gifs/machine-fly.gif",
    'Machine Pullover': "/gifs/machine-pullover.gif",
    'Machine Row': "/gifs/machine-row.gif",
    'Machine Shoulder Press': "/gifs/machine-shoulder-press.gif",
    'Medicine Ball Slam': "/gifs/medicine-ball-slam.gif",
    'Mountain Climber': "/gifs/mountain-climber.gif",
    'Overhead Press': "/gifs/overhead-press.gif",
    'Overhead Tricep Extension': "/gifs/overhead-tricep-extension.gif",
    'Pallof Press': "/gifs/pallof-press.gif",
    'Pendlay Row': "/gifs/pendlay-row.gif",
    'Plank': "/gifs/plank.gif",
    'Preacher Curl': "/gifs/preacher-curl.gif",
    'Pull-Up': "/gifs/pull-up.gif",
    'Push Press': "/gifs/push-press.gif",
    'Push-Up': "/gifs/push-up.gif",
    'Rack Pull': "/gifs/rack-pull.gif",
    'Reverse Curl': "/gifs/reverse-curl.gif",
    'Reverse Fly': "/gifs/reverse-fly.gif",
    'Reverse Lunge': "/gifs/reverse-lunge.gif",
    'Reverse Pec Deck': "/gifs/reverse-pec-deck.gif",
    'Reverse Wrist Curl': "/gifs/reverse-wrist-curl.gif",
    'Romanian Deadlift': "/gifs/romanian-deadlift.gif",
    'Rope Pushdown': "/gifs/rope-pushdown.gif",
    'Russian Twist': "/gifs/russian-twist.gif",
    'Seated Barbell Press': "/gifs/seated-barbell-press.gif",
    'Seated Cable Row': "/gifs/seated-cable-row.gif",
    'Seated Calf Raise': "/gifs/seated-calf-raise.gif",
    'Seated Dumbbell Lateral Raise': "/gifs/seated-dumbbell-lateral-raise.gif",
    'Seated Leg Curl': "/gifs/seated-leg-curl.gif",
    'Side Plank': "/gifs/side-plank.gif",
    'Single-Arm Cable Row': "/gifs/single-arm-cable-row.gif",
    'Single-Leg Romanian Deadlift': "/gifs/single-leg-romanian-deadlift.gif",
    'Skull Crusher': "/gifs/skull-crusher.gif",
    'Smith Machine Bench Press': "/gifs/smith-machine-bench-press.gif",
    'Smith Machine Squat': "/gifs/smith-machine-squat.gif",
    'Spider Curl': "/gifs/spider-curl.gif",
    'Step-Up': "/gifs/step-up.gif",
    'Straight-Arm Pulldown': "/gifs/straight-arm-pulldown.gif",
    'Sumo Deadlift': "/gifs/sumo-deadlift.gif",
    'Sumo Squat': "/gifs/sumo-squat.gif",
    'Svend Press': "/gifs/svend-press.gif",
    'T-Bar Row': "/gifs/t-bar-row.gif",
    'Toe Touch': "/gifs/toe-touch.gif",
    'Tricep Dumbbell Kickback': "/gifs/tricep-dumbbell-kickback.gif",
    'Tricep Pushdown': "/gifs/tricep-pushdown.gif",
    'V-Up': "/gifs/v-up.gif",
    'Walking Lunge': "/gifs/walking-lunge.gif",
    'Wide Push-Up': "/gifs/wide-push-up.gif",
    'Wide-Grip Pull-Up': "/gifs/wide-grip-pull-up.gif",
    'Windshield Wiper': "/gifs/windshield-wiper.gif",
    'Wrist Curl': "/gifs/wrist-curl.gif",
    'Zottman Curl': "/gifs/zottman-curl.gif",
}


async def seed_exercises() -> int:
    """Upsert the exercise library by name (user_id=None).

    Uses bulk_write with UpdateOne upserts keyed on {name, user_id: None}.
    Idempotent: re-running updates existing docs in place without changing _id.
    Returns number of operations (len of SEED_EXERCISES).
    """
    collection = Exercise.get_pymongo_collection()

    ops = [
        UpdateOne(
            filter={"name": e["name"], "user_id": None},
            update={
                "$set": {
                    "name": e["name"],
                    "muscle_group": e["muscle_group"],
                    "equipment": e["equipment"],
                    "is_custom": False,
                    "user_id": None,
                    "name_ru": e["name_ru"],
                    "gif_url": GIF_URLS.get(e["name"], e["gif_url"]),
                },
                "$setOnInsert": {
                    "_id": __import__("uuid").uuid4().__str__(),
                },
            },
            upsert=True,
        )
        for e in SEED_EXERCISES
    ]

    await collection.bulk_write(ops, ordered=False)
    return len(SEED_EXERCISES)
